[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
condition = { platforms = ["linux"]}
command = "cargo"
args = ["build","--release", "--target=aarch64-unknown-linux-musl"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = [
    "format",
    "build"
]